### ISSUE TITLE
Create / Update rotation tools

### ISSUE THREAD

**Issue by davedieter** [Denhac/KOMF-LP#14]
- Komf_hits_rotation_criteria   -  EDIT (Note: under Rotation tab)

- Komf_rotation_criteria - EDIT (Note: under Rotation tab)

- Komf_content_hours_per_week - VIEW ONLY (Note: under Rotation tab)

- Komf_rotation_ranking - VIEW ONLY (Note: under Rotation tab) 
Add “order by playWeight desc”

- Komf_hits_rotation_ranking - VIEW ONLY (Note: under Rotation tab)
Add “order by playWeight desc”

**Comment by stonaker** [comment]
All of the above changes ready on test server

**Comment by davedieter** [comment]
Many of the views on the "Manage Rotation" page do not show their description above the tables.

**Comment by stonaker** [comment]
It's because the last DB backup was from before all tables/views had comments written for them.  You should be able to change the DB and watch the comment on the page update live.
