### ISSUE TITLE
Update komf_rotation_schedule options in Tool

### ISSUE THREAD

**Issue by davedieter** [Denhac/KOMF-LP#16]
1) REMOVE possibility of scheduling "Talk Radio, News & Culture",  "Neighborhood & Community Events", "Educational & STEM"

2) ADD New "Hits" rotation choices which are seen in "radiodj.rotations" table under IDs 20-26

**Comment by stonaker** [comment]
In ThemeBlock drop-down option on "add new" row

**Comment by stonaker** [comment]
in the DB library,
getThemeBlocksForUserSelection()
change SQL query to be SELECT * FROM rotations; instead of subcats

**Comment by stonaker** [comment]
Ready on test server

**Comment by davedieter** [comment]
Looks good on test server - need to verify that it works with Radio DJ once we have connectivity back
