### ISSUE TITLE
Send metadata to KUVO in the same way we send it to tune-in

### ISSUE THREAD

**Issue by davedieter** [Denhac/KOMF-LP#27]
Send JSON formatted current-track info to:

KUVO HD3
128.177.79.122:10011

92.9FM
192.168.42.6:10011

Please let Dave know if format is TCP or UDP

**Comment by stonaker** [comment]
Code is done but failed in testing:
128.177.79.122:10011  Connection refused
192.168.42.6:10011   timed out
