### ISSUE TITLE
Add feature for uploading internal content

### ISSUE THREAD

**Issue by stonaker** [Denhac/KOMF-LP#4]
On the "manage internal content" page, we want to let users upload internal content.  The user should have the pull-down menu option to select the content type from "Underwriting" "Sweeper" "KUVO Station ID", KUVO + K225BS Station ID"  "PSA" and "Other"

which will set the following flags:  song_type, id_subcat, genre

genre will ALWAYS be 60 which is "UNKNOWN"

Underwriting:  song_Type =  4     id_subcat = 17 (Underwriting)

Sweeper:  song_Type =  2     id_subcat = 12 (KOMF Sweeper)

KUVO Station ID:  song_Type =  2     id_subcat = 15  (Station ID)

KUVO + K225BS Station ID:  song_Type =  2     id_subcat = 16  (Station ID)

PSA:  song_Type =  4     id_subcat = 20 (PSA)

Other: song_type = 6  id_subcat = 11 (unknown)

**Comment by davedieter** [comment]
File should be moved into /library/internal content/ [there are folders for each of the above subcategory types]

**Comment by stonaker** [comment]
Done as far as uploading the .mp3 file and inserting a new row into the songs table.

Open question regarding komf_track_summary ?
