### ISSUE TITLE
Add Calendar tables/views to "Manage Calendar" Page

### ISSUE THREAD

**Issue by davedieter** [Denhac/KOMF-LP#7]

**Comment by davedieter** [comment]
Includes:  

- Komf_scheduled_shows - EDIT (Note: this exists but need to add “show length”)
show_length like 01:00:00 (TIME type in the DB)
Any hour
Minutes by 0:15 precision
Seconds always :00

- Komf_consolidated_active_calendar - VIEW ONLY (Note: under Calendar tab.  This is a combination of all the below calendars)

- Komf_active_live_show_calendar - VIEW ONLY (Note: Under Calendar tab)

- Komf_active_prerec_show_calendar - VIEW ONLY (Note: Under Calendar tab)

- Komf_active_rotation_calendar - VIEW ONLY (Note: Under Calendar tab)

- Komf_live_show_calendar - EDIT    (Note: under Calendar tab)

**Comment by stonaker** [comment]
All view-only tables are in place on new "Manage Calendars" link.

**Comment by stonaker** [comment]
Added show_length to Add new row functionality for komf_scheduled_shows

**Comment by davedieter** [comment]
Looks good on test server
